#!/usr/bin/env bash

#######################
# Stuff you should edit
#######################

blogdir="/home/drew/Documents/blop_blog/"
default_author="Drew"
date_format="%B %-d, %Y"

#######################

error=false
do_error () {
	if [[ ! -z "$1" ]]; then
		echo $1
	fi
	exit
}

for file in "$blogdir"markdown/*.md; do
	meta=$(sed -ne '/^---$/,/^---$/p' $file | sed -e '/---/d')
	title=$(echo "$meta" | sed -n 's/^title:\s\?\(.*\)$/\1/p' | sed 's/"//g')
	if [[ -z "$title" ]]; then
		do_error "No title specified in $file"
	fi
	title_nospaces=$(echo "$title" | sed 's/\s/-/g')
	date=$(date -d "`stat -c %w $file`" +"%F")
	human_date=$(date -d "$date" +"$date_format" || echo "do a fucks")
	echo $title
	echo $human_date
done


